name: Check Rust code

on:
  pull_request:
    branches:
      - main
    paths:
      - rust/**

  push:
    branches:
      - main
    paths:
      - rust/**

jobs:
  generate-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check Rust code
        run: |
          cd rust
          cargo check
