name: Check Rust code

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - rust/**

  push:
    branches:
      - main
    paths:
      - rust/**

jobs:
  check-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Check Rust code
        run: |
          cd rust
          cargo check

      - name: Check Rust example
        run: |
          cd rust/example
          cargo check
