name: Generate Rust client

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  PR_BRANCH: generate-rust-${{ github.run_id }}

jobs:
  generate-rust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install virtualenv
        run: |
          pip3 install virtualenv

      - name: Generate Rust client
        run: |
          cd generate && \
          make venv && \
          source .venv/bin/activate && \
          pip3 install -r requirements.txt && \
          make rust

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Format generated Rust code
        run: |
          cd rust
          cargo fmt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Regenerate Rust client
          title: Regenerate Rust client
          branch: "${{ env.PR_BRANCH }}"
          add-paths: |
            rust/

      - name: Output
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "::notice file=,line=1::PR - ${{ steps.cpr.outputs.pull-request-url }}"
